# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f02c3d9c1881e4bde03b241c6af600389f12d79fadd83010e432e582d37f680cccff09a56189d2984d35f778938b13acbc47fc613988ad56a993204f437ebcbc

test:
  secret_key_base: f96135633c69730e2708cfe8307cc896ffc98d43b49737dcd6272c320e40682af638be6f37ed05c43e7f17dc431d0a635b317702c1592c28751963a97419aec8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
